version: '3.1'

services:
  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"

  nodeapp:
    build:
      context: .
    restart: always
    environment:
      DB_HOST: mongodb://mongo:27017/posts
    ports:
        - "3000:3000"